language: python # => 1
python: # => 2
      - "3.8"
services: # => 3

      - mysql

    env: # => 4

      -DJANGO=1.8 DB=mysql
    install: # => 5

      - pip install -r requirements.txt